---
- hosts: all
  tasks:

  # -------------------------------------------------------------------
  # Set up OS.
  # -------------------------------------------------------------------

  - name: set timezone to UTC
    file: src=/usr/share/zoneinfo/UTC dest=/etc/localtime force=yes state=link

  # -------------------------------------------------------------------
  # Install software.
  # -------------------------------------------------------------------

  - name: install epel repo
    yum: name=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

  - name: install go
    yum: name=golang state=latest

  - name: install misc
    yum: name={{item}} state=latest
    with_items:
    - git
    - vim
    - htop
    - tmux
    - tree
    - mercurial

  # -------------------------------------------------------------------
  # Set up application.
  # -------------------------------------------------------------------

  - name: set environment variables
    lineinfile: dest=/home/vagrant/.bashrc state=present line="{{item}}"
    with_items:
    - export PATH=$PATH:/go/bin
    - export GOPATH=/go
